# coding: utf-8

"""
    WHMCS API

    Python client for the WHMCS API.  WHMCS (Web Host Manager Complete Solution) provides a single API endpoint that handles multiple operations through different 'action' parameters. This specification presents each action as an independent path while routing all requests to the /api.php endpoint. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from whmcs_client.models.get_clients_domains_response_all_of_domains_one_of import GetClientsDomainsResponseAllOfDomainsOneOf

class TestGetClientsDomainsResponseAllOfDomainsOneOf(unittest.TestCase):
    """GetClientsDomainsResponseAllOfDomainsOneOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetClientsDomainsResponseAllOfDomainsOneOf:
        """Test GetClientsDomainsResponseAllOfDomainsOneOf
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetClientsDomainsResponseAllOfDomainsOneOf`
        """
        model = GetClientsDomainsResponseAllOfDomainsOneOf()
        if include_optional:
            return GetClientsDomainsResponseAllOfDomainsOneOf(
                domain = [
                    whmcs_client.models.domain_info.DomainInfo(
                        id = 56, 
                        userid = 56, 
                        orderid = 56, 
                        regtype = '', 
                        domainname = '', 
                        registrar = '', 
                        regperiod = 56, 
                        firstpaymentamount = 1.337, 
                        recurringamount = 1.337, 
                        paymentmethod = '', 
                        paymentmethodname = '', 
                        regdate = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        expirydate = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        nextduedate = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        status = '', 
                        subscriptionid = '', 
                        promoid = 56, 
                        dnsmanagement = True, 
                        emailforwarding = True, 
                        idprotection = True, 
                        donotrenew = True, 
                        notes = '', )
                    ]
            )
        else:
            return GetClientsDomainsResponseAllOfDomainsOneOf(
        )
        """

    def testGetClientsDomainsResponseAllOfDomainsOneOf(self):
        """Test GetClientsDomainsResponseAllOfDomainsOneOf"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
