# coding: utf-8

"""
    WHMCS API

    Python client for the WHMCS API.  WHMCS (Web Host Manager Complete Solution) provides a single API endpoint that handles multiple operations through different 'action' parameters. This client supports various WHMCS operations for managing clients, orders, and other resources.  Authentication is handled through username/password or API credentials. All requests are sent as form-encoded data to the /api.php endpoint. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from whmcs_client.models.add_order_response import AddOrderResponse

class TestAddOrderResponse(unittest.TestCase):
    """AddOrderResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddOrderResponse:
        """Test AddOrderResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddOrderResponse`
        """
        model = AddOrderResponse()
        if include_optional:
            return AddOrderResponse(
                result = 'success',
                action = 'AddOrder',
                warnings = [
                    ''
                    ],
                message = '',
                orderid = '',
                serviceids = '',
                addonids = '',
                domainids = '',
                invoiceid = 56
            )
        else:
            return AddOrderResponse(
                result = 'success',
                action = 'AddOrder',
        )
        """

    def testAddOrderResponse(self):
        """Test AddOrderResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
