# coding: utf-8

"""
    WHMCS API

    Python client for the WHMCS API.  WHMCS (Web Host Manager Complete Solution) provides a single API endpoint that handles multiple operations through different 'action' parameters. This client supports various WHMCS operations for managing clients, orders, and other resources.  Authentication is handled through username/password or API credentials. All requests are sent as form-encoded data to the /api.php endpoint.   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import whmcs_client
from whmcs_client.models.add_client_response import AddClientResponse  # noqa: E501
from whmcs_client.rest import ApiException


class TestAddClientResponse(unittest.TestCase):
    """AddClientResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddClientResponse(self):
        """Test AddClientResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = whmcs_client.models.add_client_response.AddClientResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
