# coding: utf-8

"""
    WHMCS API

    Python client for the WHMCS API.  WHMCS (Web Host Manager Complete Solution) provides a single API endpoint that handles multiple operations through different 'action' parameters. This specification presents each action as an independent path while routing all requests to the /api.php endpoint. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from whmcs_client.models.get_currencies_response import GetCurrenciesResponse

class TestGetCurrenciesResponse(unittest.TestCase):
    """GetCurrenciesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetCurrenciesResponse:
        """Test GetCurrenciesResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetCurrenciesResponse`
        """
        model = GetCurrenciesResponse()
        if include_optional:
            return GetCurrenciesResponse(
                result = 'success',
                message = '',
                totalresults = 56,
                currencies = whmcs_client.models.get_currencies_response_all_of_currencies.GetCurrenciesResponse_allOf_currencies(
                    currency = [
                        whmcs_client.models.currency_info.CurrencyInfo(
                            id = 56, 
                            code = '', 
                            prefix = '', 
                            suffix = '', 
                            format = 56, 
                            rate = '', )
                        ], )
            )
        else:
            return GetCurrenciesResponse(
        )
        """

    def testGetCurrenciesResponse(self):
        """Test GetCurrenciesResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
