# coding: utf-8

"""
    WHMCS API

    Python client for the WHMCS API.  WHMCS (Web Host Manager Complete Solution) provides a single API endpoint that handles multiple operations through different 'action' parameters. This client supports various WHMCS operations for managing clients, orders, and other resources.  Authentication is handled through username/password or API credentials. All requests are sent as form-encoded data to the /api.php endpoint. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from whmcs_client.models.api_post_request import ApiPostRequest

class TestApiPostRequest(unittest.TestCase):
    """ApiPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiPostRequest:
        """Test ApiPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiPostRequest`
        """
        model = ApiPostRequest()
        if include_optional:
            return ApiPostRequest(
                username = '',
                password = '',
                accesskey = '',
                responsetype = 'json',
                action = 'AddOrder',
                owner_user_id = 56,
                firstname = '',
                lastname = '',
                companyname = '',
                email = '',
                address1 = '',
                address2 = '',
                city = '',
                state = '',
                postcode = '',
                country = '',
                phonenumber = '',
                tax_id = '',
                password2 = '',
                securityqid = 56,
                securityqans = '',
                currency = 56,
                groupid = 56,
                customfields = [
                    ''
                    ],
                language = '',
                clientip = '',
                notes = '',
                marketingoptin = True,
                noemail = True,
                skipvalidation = True,
                clientid = 56,
                clientemail = '',
                status = '',
                paymentmethod = '',
                email_preferences_general = True,
                email_preferences_product = True,
                email_preferences_domain = True,
                email_preferences_invoice = True,
                email_preferences_support = True,
                email_preferences_affiliate = True,
                clearcreditcard = True,
                latefeeoveride = True,
                overideduenotices = True,
                taxexempt = True,
                separateinvoices = True,
                disableautocc = True,
                overrideautoclose = True,
                pid = [
                    56
                    ],
                qty = [
                    56
                    ],
                domain = [
                    ''
                    ],
                billingcycle = [
                    'monthly'
                    ],
                domaintype = [
                    'register'
                    ],
                regperiod = [
                    1
                    ],
                idnlanguage = [
                    ''
                    ],
                eppcode = [
                    ''
                    ],
                nameserver1 = '',
                nameserver2 = '',
                nameserver3 = '',
                nameserver4 = '',
                nameserver5 = '',
                configoptions = [
                    ''
                    ],
                priceoverride = [
                    1.337
                    ],
                promocode = '',
                promooverride = True,
                affid = 56,
                noinvoice = True,
                noinvoiceemail = True,
                addons = [
                    ''
                    ],
                addonsqty = [
                    ''
                    ],
                hostname = [
                    ''
                    ],
                ns1prefix = [
                    ''
                    ],
                ns2prefix = [
                    ''
                    ],
                rootpw = [
                    ''
                    ],
                contactid = 56,
                dnsmanagement = [
                    True
                    ],
                domainfields = [
                    ''
                    ],
                emailforwarding = [
                    True
                    ],
                idprotection = [
                    True
                    ],
                domainpriceoverride = [
                    1.337
                    ],
                domainrenewoverride = [
                    1.337
                    ],
                domainrenewals = {
                    'key' : 56
                    },
                addonid = 56,
                addonidqty = 56,
                serviceid = 56,
                addonids = [
                    56
                    ],
                addonidsqty = [
                    56
                    ],
                serviceids = [
                    56
                    ],
                servicerenewals = [
                    56
                    ],
                addonrenewals = [
                    56
                    ]
            )
        else:
            return ApiPostRequest(
                username = '',
                password = '',
                action = 'AddOrder',
                firstname = '',
                lastname = '',
                email = '',
                address1 = '',
                city = '',
                state = '',
                postcode = '',
                country = '',
                phonenumber = '',
                clientid = 56,
                paymentmethod = '',
        )
        """

    def testApiPostRequest(self):
        """Test ApiPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
