# coding: utf-8

"""
    WHMCS API

    Python client for the WHMCS API.  WHMCS (Web Host Manager Complete Solution) provides a single API endpoint that handles multiple operations through different 'action' parameters. This specification presents each action as an independent path while routing all requests to the /api.php endpoint.   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import whmcs_client
from whmcs_client.models.whmcs_base_request import WHMCSBaseRequest  # noqa: E501
from whmcs_client.rest import ApiException


class TestWHMCSBaseRequest(unittest.TestCase):
    """WHMCSBaseRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWHMCSBaseRequest(self):
        """Test WHMCSBaseRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = whmcs_client.models.whmcs_base_request.WHMCSBaseRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
