# coding: utf-8

"""
    WHMCS API

    OpenAPI specification for the WHMCS API endpoints.  This specification uses discriminators to properly handle polymorphic request/response schemas. The 'action' field serves as the discriminator property to differentiate between different request and response types (AddClient, UpdateClient, AddOrder).   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import whmcs_client
from whmcs_client.models.update_client_request import UpdateClientRequest  # noqa: E501
from whmcs_client.rest import ApiException


class TestUpdateClientRequest(unittest.TestCase):
    """UpdateClientRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateClientRequest(self):
        """Test UpdateClientRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = whmcs_client.models.update_client_request.UpdateClientRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
