# coding: utf-8

"""
    WHMCS API

    Python client for the WHMCS API.  WHMCS (Web Host Manager Complete Solution) provides a single API endpoint that handles multiple operations through different 'action' parameters. This specification presents each action as an independent path while routing all requests to the /api.php endpoint. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from whmcs_client.models.product_info import ProductInfo

class TestProductInfo(unittest.TestCase):
    """ProductInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProductInfo:
        """Test ProductInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProductInfo`
        """
        model = ProductInfo()
        if include_optional:
            return ProductInfo(
                id = None,
                qty = None,
                clientid = None,
                orderid = None,
                ordernumber = '',
                pid = None,
                regdate = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                name = '',
                translated_name = '',
                groupname = '',
                translated_groupname = '',
                domain = '',
                dedicatedip = '',
                serverid = None,
                servername = '',
                serverip = '',
                serverhostname = '',
                suspensionreason = '',
                firstpaymentamount = '',
                recurringamount = '',
                paymentmethod = '',
                paymentmethodname = '',
                billingcycle = '',
                nextduedate = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                status = '',
                username = '',
                password = '',
                subscriptionid = '',
                promoid = None,
                overideautosuspend = '',
                overidesuspenduntil = '',
                ns1 = '',
                ns2 = '',
                assignedips = '',
                notes = '',
                diskusage = '',
                disklimit = '',
                bwusage = '',
                bwlimit = '',
                lastupdate = '',
                customfields = { },
                configoptions = { }
            )
        else:
            return ProductInfo(
        )
        """

    def testProductInfo(self):
        """Test ProductInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
