# coding: utf-8

"""
    WHMCS API

    Python client for the WHMCS API.  WHMCS (Web Host Manager Complete Solution) provides a single API endpoint that handles multiple operations through different 'action' parameters. This client supports various WHMCS operations for managing clients, orders, and other resources.  Authentication is handled through username/password or API credentials. All requests are sent as form-encoded data to the /api.php endpoint. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from whmcs_client.models.update_client_request import UpdateClientRequest

class TestUpdateClientRequest(unittest.TestCase):
    """UpdateClientRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateClientRequest:
        """Test UpdateClientRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateClientRequest`
        """
        model = UpdateClientRequest()
        if include_optional:
            return UpdateClientRequest(
                username = '',
                password = '',
                accesskey = '',
                responsetype = 'json',
                action = 'UpdateClient',
                clientid = 56,
                clientemail = '',
                firstname = '',
                lastname = '',
                companyname = '',
                email = '',
                address1 = '',
                address2 = '',
                city = '',
                state = '',
                postcode = '',
                country = '',
                phonenumber = '',
                tax_id = '',
                currency = 56,
                groupid = 56,
                customfields = '',
                language = '',
                clientip = '',
                notes = '',
                status = '',
                paymentmethod = '',
                email_preferences_general = True,
                email_preferences_product = True,
                email_preferences_domain = True,
                email_preferences_invoice = True,
                email_preferences_support = True,
                email_preferences_affiliate = True,
                marketingoptin = True,
                clearcreditcard = True,
                skipvalidation = True,
                latefeeoveride = True,
                overideduenotices = True,
                taxexempt = True,
                separateinvoices = True,
                disableautocc = True,
                overrideautoclose = True
            )
        else:
            return UpdateClientRequest(
                username = '',
                password = '',
                action = 'UpdateClient',
        )
        """

    def testUpdateClientRequest(self):
        """Test UpdateClientRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
