# coding: utf-8

"""
    WHMCS API

    Python client for the WHMCS API.  WHMCS (Web Host Manager Complete Solution) provides a single API endpoint that handles multiple operations through different 'action' parameters. This specification presents each action as an independent path while routing all requests to the /api.php endpoint.   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import whmcs_client
from whmcs_client.models.update_client_body import UpdateClientBody  # noqa: E501
from whmcs_client.rest import ApiException


class TestUpdateClientBody(unittest.TestCase):
    """UpdateClientBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateClientBody(self):
        """Test UpdateClientBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = whmcs_client.models.update_client_body.UpdateClientBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
