# coding: utf-8

"""
    WHMCS API

    Python client for the WHMCS API.  WHMCS (Web Host Manager Complete Solution) provides a single API endpoint that handles multiple operations through different 'action' parameters. This specification presents each action as an independent path while routing all requests to the /api.php endpoint. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from whmcs_client.models.get_clients_response import GetClientsResponse

class TestGetClientsResponse(unittest.TestCase):
    """GetClientsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetClientsResponse:
        """Test GetClientsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetClientsResponse`
        """
        model = GetClientsResponse()
        if include_optional:
            return GetClientsResponse(
                result = 'success',
                message = '',
                totalresults = 56,
                startnumber = 56,
                numreturned = 56,
                clients = whmcs_client.models.get_clients_response_all_of_clients.GetClientsResponse_allOf_clients(
                    client = [
                        whmcs_client.models.client_info.ClientInfo(
                            id = 56, 
                            firstname = '', 
                            lastname = '', 
                            companyname = '', 
                            email = '', 
                            datecreated = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                            groupid = 56, 
                            status = '', )
                        ], )
            )
        else:
            return GetClientsResponse(
        )
        """

    def testGetClientsResponse(self):
        """Test GetClientsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
