# coding: utf-8

"""
    WHMCS API

    Python client for the WHMCS API.  WHMCS (Web Host Manager Complete Solution) provides a single API endpoint that handles multiple operations through different 'action' parameters. This specification presents each action as an independent path while routing all requests to the /api.php endpoint. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from whmcs_client.models.transaction_info import TransactionInfo

class TestTransactionInfo(unittest.TestCase):
    """TransactionInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TransactionInfo:
        """Test TransactionInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TransactionInfo`
        """
        model = TransactionInfo()
        if include_optional:
            return TransactionInfo(
                id = 56,
                userid = 56,
                currency = 56,
                gateway = '',
                var_date = '',
                description = '',
                amountin = 1.337,
                fees = 1.337,
                amountout = 1.337,
                rate = '',
                transid = '',
                invoiceid = 56,
                refundid = 56
            )
        else:
            return TransactionInfo(
        )
        """

    def testTransactionInfo(self):
        """Test TransactionInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
