# coding: utf-8

"""
    WHMCS API

    Python client for the WHMCS API.  WHMCS (Web Host Manager Complete Solution) provides a single API endpoint that handles multiple operations through different 'action' parameters. This client supports various WHMCS operations for managing clients, orders, and other resources.  Authentication is handled through username/password or API credentials. All requests are sent as form-encoded data to the /api.php endpoint. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from whmcs_client.models.add_order_request import AddOrderRequest

class TestAddOrderRequest(unittest.TestCase):
    """AddOrderRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddOrderRequest:
        """Test AddOrderRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddOrderRequest`
        """
        model = AddOrderRequest()
        if include_optional:
            return AddOrderRequest(
                username = '',
                password = '',
                accesskey = '',
                responsetype = 'json',
                action = 'AddOrder',
                clientid = 56,
                paymentmethod = '',
                pid = [
                    56
                    ],
                qty = [
                    56
                    ],
                domain = [
                    ''
                    ],
                billingcycle = [
                    'monthly'
                    ],
                domaintype = [
                    'register'
                    ],
                regperiod = [
                    1
                    ],
                idnlanguage = [
                    ''
                    ],
                eppcode = [
                    ''
                    ],
                nameserver1 = '',
                nameserver2 = '',
                nameserver3 = '',
                nameserver4 = '',
                nameserver5 = '',
                customfields = [
                    ''
                    ],
                configoptions = [
                    ''
                    ],
                priceoverride = [
                    1.337
                    ],
                promocode = '',
                promooverride = True,
                affid = 56,
                noinvoice = True,
                noinvoiceemail = True,
                noemail = True,
                addons = [
                    ''
                    ],
                addonsqty = [
                    ''
                    ],
                hostname = [
                    ''
                    ],
                ns1prefix = [
                    ''
                    ],
                ns2prefix = [
                    ''
                    ],
                rootpw = [
                    ''
                    ],
                contactid = 56,
                dnsmanagement = [
                    True
                    ],
                domainfields = [
                    ''
                    ],
                emailforwarding = [
                    True
                    ],
                idprotection = [
                    True
                    ],
                domainpriceoverride = [
                    1.337
                    ],
                domainrenewoverride = [
                    1.337
                    ],
                domainrenewals = {
                    'key' : 56
                    },
                clientip = '',
                addonid = 56,
                addonidqty = 56,
                serviceid = 56,
                addonids = [
                    56
                    ],
                addonidsqty = [
                    56
                    ],
                serviceids = [
                    56
                    ],
                servicerenewals = [
                    56
                    ],
                addonrenewals = [
                    56
                    ]
            )
        else:
            return AddOrderRequest(
                username = '',
                password = '',
                action = 'AddOrder',
                clientid = 56,
                paymentmethod = '',
        )
        """

    def testAddOrderRequest(self):
        """Test AddOrderRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
