# coding: utf-8

"""
    WHMCS API

    Python client for the WHMCS API.  WHMCS (Web Host Manager Complete Solution) provides a single API endpoint that handles multiple operations through different 'action' parameters. This specification presents each action as an independent path while routing all requests to the /api.php endpoint. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from whmcs_client.models.affiliate_info import AffiliateInfo

class TestAffiliateInfo(unittest.TestCase):
    """AffiliateInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AffiliateInfo:
        """Test AffiliateInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AffiliateInfo`
        """
        model = AffiliateInfo()
        if include_optional:
            return AffiliateInfo(
                id = 56,
                var_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                clientid = 56,
                visitors = 56,
                paytype = '',
                payamount = 1.337,
                onetime = 56,
                balance = 1.337,
                withdrawn = 1.337,
                created_at = '',
                updated_at = ''
            )
        else:
            return AffiliateInfo(
        )
        """

    def testAffiliateInfo(self):
        """Test AffiliateInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
