# coding: utf-8

"""
    WHMCS API

    Python client for the WHMCS API.  WHMCS (Web Host Manager Complete Solution) provides a single API endpoint that handles multiple operations through different 'action' parameters. This specification presents each action as an independent path while routing all requests to the /api.php endpoint. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from whmcs_client.models.domain_get_nameservers_response import DomainGetNameserversResponse

class TestDomainGetNameserversResponse(unittest.TestCase):
    """DomainGetNameserversResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DomainGetNameserversResponse:
        """Test DomainGetNameserversResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DomainGetNameserversResponse`
        """
        model = DomainGetNameserversResponse()
        if include_optional:
            return DomainGetNameserversResponse(
                result = 'success',
                message = '',
                ns1 = '',
                ns2 = '',
                ns3 = '',
                ns4 = '',
                ns5 = ''
            )
        else:
            return DomainGetNameserversResponse(
        )
        """

    def testDomainGetNameserversResponse(self):
        """Test DomainGetNameserversResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
