# coding: utf-8

"""
    WHMCS API

    Python client for the WHMCS API.  WHMCS (Web Host Manager Complete Solution) provides a single API endpoint that handles multiple operations through different 'action' parameters. This specification presents each action as an independent path while routing all requests to the /api.php endpoint. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from whmcs_client.models.get_payment_methods_response import GetPaymentMethodsResponse

class TestGetPaymentMethodsResponse(unittest.TestCase):
    """GetPaymentMethodsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetPaymentMethodsResponse:
        """Test GetPaymentMethodsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetPaymentMethodsResponse`
        """
        model = GetPaymentMethodsResponse()
        if include_optional:
            return GetPaymentMethodsResponse(
                result = 'success',
                message = '',
                totalresults = 56,
                paymentmethods = whmcs_client.models.get_payment_methods_response_all_of_paymentmethods.GetPaymentMethodsResponse_allOf_paymentmethods(
                    paymentmethod = [
                        whmcs_client.models.payment_method_info.PaymentMethodInfo(
                            module = '', 
                            displayname = '', )
                        ], )
            )
        else:
            return GetPaymentMethodsResponse(
        )
        """

    def testGetPaymentMethodsResponse(self):
        """Test GetPaymentMethodsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
