# coding: utf-8

"""
    WHMCS API

    Python client for the WHMCS API.  WHMCS (Web Host Manager Complete Solution) provides a single API endpoint that handles multiple operations through different 'action' parameters. This specification presents each action as an independent path while routing all requests to the /api.php endpoint. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from whmcs_client.models.client_details_info import ClientDetailsInfo

class TestClientDetailsInfo(unittest.TestCase):
    """ClientDetailsInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ClientDetailsInfo:
        """Test ClientDetailsInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ClientDetailsInfo`
        """
        model = ClientDetailsInfo()
        if include_optional:
            return ClientDetailsInfo(
                client_id = 56,
                owner_user_id = 56,
                userid = 56,
                id = 56,
                uuid = '',
                firstname = '',
                lastname = '',
                fullname = '',
                companyname = '',
                email = '',
                address1 = '',
                address2 = '',
                city = '',
                fullstate = '',
                state = '',
                postcode = '',
                countrycode = '',
                country = '',
                phonenumber = '',
                tax_id = '',
                email_preferences = { },
                statecode = '',
                countryname = '',
                phonecc = '',
                phonenumberformatted = '',
                telephone_number = '',
                billingcid = 56,
                notes = '',
                currency = 56,
                defaultgateway = '',
                groupid = 56,
                status = '',
                credit = '',
                taxexempt = True,
                latefeeoveride = True,
                overideduenotices = True,
                separateinvoices = True,
                disableautocc = True,
                emailoptout = True,
                marketing_emails_opt_in = True,
                overrideautoclose = True,
                allow_single_sign_on = None,
                email_verified = True,
                language = '',
                is_opted_in_to_marketing_emails = True,
                lastlogin = '',
                currency_code = '',
                customfields = None,
                users = whmcs_client.models.user_collection.UserCollection(
                    user = null, )
            )
        else:
            return ClientDetailsInfo(
        )
        """

    def testClientDetailsInfo(self):
        """Test ClientDetailsInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
