# coding: utf-8

"""
    WHMCS API

    Python client for the WHMCS API.  WHMCS (Web Host Manager Complete Solution) provides a single API endpoint that handles multiple operations through different 'action' parameters. This specification presents each action as an independent path while routing all requests to the /api.php endpoint. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from whmcs_client.models.invoice_collection_invoice import InvoiceCollectionInvoice

class TestInvoiceCollectionInvoice(unittest.TestCase):
    """InvoiceCollectionInvoice unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InvoiceCollectionInvoice:
        """Test InvoiceCollectionInvoice
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InvoiceCollectionInvoice`
        """
        model = InvoiceCollectionInvoice()
        if include_optional:
            return InvoiceCollectionInvoice(
                id = 56,
                userid = 56,
                firstname = '',
                lastname = '',
                companyname = '',
                invoicenum = '',
                var_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                duedate = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                datepaid = '',
                last_capture_attempt = '',
                date_refunded = '',
                date_cancelled = '',
                subtotal = '',
                credit = '',
                tax = '',
                tax2 = '',
                total = '',
                taxrate = '',
                taxrate2 = '',
                status = '',
                paymentmethod = '',
                paymethodid = None,
                notes = '',
                created_at = '',
                updated_at = '',
                currencycode = '',
                currencyprefix = '',
                currencysuffix = ''
            )
        else:
            return InvoiceCollectionInvoice(
        )
        """

    def testInvoiceCollectionInvoice(self):
        """Test InvoiceCollectionInvoice"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
