# coding: utf-8

"""
    WHMCS API

    Python client for the WHMCS API.  WHMCS (Web Host Manager Complete Solution) provides a single API endpoint that handles multiple operations through different 'action' parameters. This specification presents each action as an independent path while routing all requests to the /api.php endpoint.   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from whmcs_client.models.whmcs_success_response import WHMCSSuccessResponse  # noqa: F401,E501

class AddClientResponse(WHMCSSuccessResponse):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'clientid': 'int',
        'owner_user_id': 'int'
    }
    if hasattr(WHMCSSuccessResponse, "swagger_types"):
        swagger_types.update(WHMCSSuccessResponse.swagger_types)

    attribute_map = {
        'clientid': 'clientid',
        'owner_user_id': 'owner_user_id'
    }
    if hasattr(WHMCSSuccessResponse, "attribute_map"):
        attribute_map.update(WHMCSSuccessResponse.attribute_map)

    def __init__(self, clientid=None, owner_user_id=None, *args, **kwargs):  # noqa: E501
        """AddClientResponse - a model defined in Swagger"""  # noqa: E501
        self._clientid = None
        self._owner_user_id = None
        self.discriminator = None
        if clientid is not None:
            self.clientid = clientid
        if owner_user_id is not None:
            self.owner_user_id = owner_user_id
        WHMCSSuccessResponse.__init__(self, *args, **kwargs)

    @property
    def clientid(self):
        """Gets the clientid of this AddClientResponse.  # noqa: E501

        The ID of the newly created client  # noqa: E501

        :return: The clientid of this AddClientResponse.  # noqa: E501
        :rtype: int
        """
        return self._clientid

    @clientid.setter
    def clientid(self, clientid):
        """Sets the clientid of this AddClientResponse.

        The ID of the newly created client  # noqa: E501

        :param clientid: The clientid of this AddClientResponse.  # noqa: E501
        :type: int
        """

        self._clientid = clientid

    @property
    def owner_user_id(self):
        """Gets the owner_user_id of this AddClientResponse.  # noqa: E501

        The ID of the user that owns the client  # noqa: E501

        :return: The owner_user_id of this AddClientResponse.  # noqa: E501
        :rtype: int
        """
        return self._owner_user_id

    @owner_user_id.setter
    def owner_user_id(self, owner_user_id):
        """Sets the owner_user_id of this AddClientResponse.

        The ID of the user that owns the client  # noqa: E501

        :param owner_user_id: The owner_user_id of this AddClientResponse.  # noqa: E501
        :type: int
        """

        self._owner_user_id = owner_user_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AddClientResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AddClientResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
