# coding: utf-8

"""
    WHMCS API

    Python client for the WHMCS API.  WHMCS (Web Host Manager Complete Solution) provides a single API endpoint that handles multiple operations through different 'action' parameters. This specification presents each action as an independent path while routing all requests to the /api.php endpoint. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AffiliateInfo(BaseModel):
    """
    AffiliateInfo
    """ # noqa: E501
    id: Optional[StrictInt] = Field(default=None, description="The affiliate ID")
    var_date: Optional[date] = Field(default=None, description="The affiliate date", alias="date")
    clientid: Optional[StrictInt] = Field(default=None, description="The client ID")
    visitors: Optional[StrictInt] = Field(default=None, description="The visitor count")
    paytype: Optional[StrictStr] = Field(default=None, description="The affiliate pay type")
    payamount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The payout amount")
    onetime: Optional[StrictInt] = Field(default=None, description="Whether the affiliate is one time")
    balance: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The current balance")
    withdrawn: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The withdrawn amount")
    created_at: Optional[StrictStr] = Field(default=None, description="The creation timestamp")
    updated_at: Optional[StrictStr] = Field(default=None, description="The last update timestamp")
    __properties: ClassVar[List[str]] = ["id", "date", "clientid", "visitors", "paytype", "payamount", "onetime", "balance", "withdrawn", "created_at", "updated_at"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AffiliateInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AffiliateInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "date": obj.get("date"),
            "clientid": obj.get("clientid"),
            "visitors": obj.get("visitors"),
            "paytype": obj.get("paytype"),
            "payamount": obj.get("payamount"),
            "onetime": obj.get("onetime"),
            "balance": obj.get("balance"),
            "withdrawn": obj.get("withdrawn"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


