# coding: utf-8

"""
    WHMCS API

    Python client for the WHMCS API.  WHMCS (Web Host Manager Complete Solution) provides a single API endpoint that handles multiple operations through different 'action' parameters. This specification presents each action as an independent path while routing all requests to the /api.php endpoint. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DomainInfo(BaseModel):
    """
    DomainInfo
    """ # noqa: E501
    id: Optional[StrictInt] = Field(default=None, description="The domain ID")
    userid: Optional[StrictInt] = Field(default=None, description="The client ID that owns the domain")
    orderid: Optional[StrictInt] = Field(default=None, description="The order ID associated with the domain")
    regtype: Optional[StrictStr] = Field(default=None, description="The registration type, such as Register or Transfer")
    domainname: Optional[StrictStr] = Field(default=None, description="The domain name")
    registrar: Optional[StrictStr] = Field(default=None, description="The registrar module name")
    regperiod: Optional[StrictInt] = Field(default=None, description="The registration period")
    firstpaymentamount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The first payment amount")
    recurringamount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The recurring amount")
    paymentmethod: Optional[StrictStr] = Field(default=None, description="The payment method code")
    paymentmethodname: Optional[StrictStr] = Field(default=None, description="The payment method name")
    regdate: Optional[date] = Field(default=None, description="The registration date")
    expirydate: Optional[date] = Field(default=None, description="The expiration date")
    nextduedate: Optional[date] = Field(default=None, description="The next due date")
    status: Optional[StrictStr] = Field(default=None, description="The domain status")
    subscriptionid: Optional[StrictStr] = Field(default=None, description="The subscription identifier")
    promoid: Optional[StrictInt] = Field(default=None, description="The promotion ID")
    dnsmanagement: Optional[StrictBool] = Field(default=None, description="Whether DNS management is enabled")
    emailforwarding: Optional[StrictBool] = Field(default=None, description="Whether email forwarding is enabled")
    idprotection: Optional[StrictBool] = Field(default=None, description="Whether ID protection is enabled")
    donotrenew: Optional[StrictBool] = Field(default=None, description="Whether the domain should not renew")
    notes: Optional[StrictStr] = Field(default=None, description="Internal notes for the domain")
    __properties: ClassVar[List[str]] = ["id", "userid", "orderid", "regtype", "domainname", "registrar", "regperiod", "firstpaymentamount", "recurringamount", "paymentmethod", "paymentmethodname", "regdate", "expirydate", "nextduedate", "status", "subscriptionid", "promoid", "dnsmanagement", "emailforwarding", "idprotection", "donotrenew", "notes"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DomainInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DomainInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "userid": obj.get("userid"),
            "orderid": obj.get("orderid"),
            "regtype": obj.get("regtype"),
            "domainname": obj.get("domainname"),
            "registrar": obj.get("registrar"),
            "regperiod": obj.get("regperiod"),
            "firstpaymentamount": obj.get("firstpaymentamount"),
            "recurringamount": obj.get("recurringamount"),
            "paymentmethod": obj.get("paymentmethod"),
            "paymentmethodname": obj.get("paymentmethodname"),
            "regdate": obj.get("regdate"),
            "expirydate": obj.get("expirydate"),
            "nextduedate": obj.get("nextduedate"),
            "status": obj.get("status"),
            "subscriptionid": obj.get("subscriptionid"),
            "promoid": obj.get("promoid"),
            "dnsmanagement": obj.get("dnsmanagement"),
            "emailforwarding": obj.get("emailforwarding"),
            "idprotection": obj.get("idprotection"),
            "donotrenew": obj.get("donotrenew"),
            "notes": obj.get("notes")
        })
        return _obj


