# coding: utf-8

"""
    WHMCS API

    Python client for the WHMCS API.  WHMCS (Web Host Manager Complete Solution) provides a single API endpoint that handles multiple operations through different 'action' parameters. This specification presents each action as an independent path while routing all requests to the /api.php endpoint. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from whmcs_client.models.product_collection import ProductCollection
from typing import Optional, Set
from typing_extensions import Self

class GetClientsProductsResponse(BaseModel):
    """
    GetClientsProductsResponse
    """ # noqa: E501
    result: Optional[StrictStr] = None
    message: Optional[StrictStr] = Field(default=None, description="Response message")
    clientid: Optional[StrictStr] = Field(default=None, description="The specific client id searched for")
    serviceid: Optional[StrictStr] = Field(default=None, description="The specific service id searched for")
    pid: Optional[StrictStr] = Field(default=None, description="The specific product id searched for")
    domain: Optional[StrictStr] = Field(default=None, description="The specific domain searched for")
    totalresults: Optional[StrictStr] = Field(default=None, description="The total number of results available")
    startnumber: Optional[StrictInt] = Field(default=None, description="The starting number for the returned results")
    numreturned: Optional[StrictInt] = Field(default=None, description="The number of results returned")
    products: Optional[ProductCollection] = None
    __properties: ClassVar[List[str]] = ["result", "message", "clientid", "serviceid", "pid", "domain", "totalresults", "startnumber", "numreturned", "products"]

    @field_validator('result')
    def result_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['success']):
            raise ValueError("must be one of enum values ('success')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetClientsProductsResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of products
        if self.products:
            _dict['products'] = self.products.to_dict()
        # set to None if serviceid (nullable) is None
        # and model_fields_set contains the field
        if self.serviceid is None and "serviceid" in self.model_fields_set:
            _dict['serviceid'] = None

        # set to None if pid (nullable) is None
        # and model_fields_set contains the field
        if self.pid is None and "pid" in self.model_fields_set:
            _dict['pid'] = None

        # set to None if domain (nullable) is None
        # and model_fields_set contains the field
        if self.domain is None and "domain" in self.model_fields_set:
            _dict['domain'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetClientsProductsResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "result": obj.get("result"),
            "message": obj.get("message"),
            "clientid": obj.get("clientid"),
            "serviceid": obj.get("serviceid"),
            "pid": obj.get("pid"),
            "domain": obj.get("domain"),
            "totalresults": obj.get("totalresults"),
            "startnumber": obj.get("startnumber"),
            "numreturned": obj.get("numreturned"),
            "products": ProductCollection.from_dict(obj["products"]) if obj.get("products") is not None else None
        })
        return _obj


