# coding: utf-8

"""
    WHMCS API

    Python client for the WHMCS API.  WHMCS (Web Host Manager Complete Solution) provides a single API endpoint that handles multiple operations through different 'action' parameters. This specification presents each action as an independent path while routing all requests to the /api.php endpoint. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from whmcs_client.models.currency_info import CurrencyInfo
from whmcs_client.models.tld_pricing_info import TldPricingInfo
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class GetTLDPricingResponse(BaseModel):
    """
    GetTLDPricingResponse
    """ # noqa: E501
    result: Optional[StrictStr] = None
    message: Optional[StrictStr] = Field(default=None, description="Response message")
    currency: Optional[CurrencyInfo] = None
    pricing: Optional[Dict[str, TldPricingInfo]] = None
    __properties: ClassVar[List[str]] = ["result", "message", "currency", "pricing"]

    @field_validator('result')
    def result_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['success', 'error']):
            raise ValueError("must be one of enum values ('success', 'error')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetTLDPricingResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of currency
        if self.currency:
            _dict['currency'] = self.currency.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each value in pricing (dict)
        _field_dict = {}
        if self.pricing:
            for _key_pricing in self.pricing:
                if self.pricing[_key_pricing]:
                    _field_dict[_key_pricing] = self.pricing[_key_pricing].to_dict()
            _dict['pricing'] = _field_dict
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetTLDPricingResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "result": obj.get("result"),
            "message": obj.get("message"),
            "currency": CurrencyInfo.from_dict(obj["currency"]) if obj.get("currency") is not None else None,
            "pricing": dict(
                (_k, TldPricingInfo.from_dict(_v))
                for _k, _v in obj["pricing"].items()
            )
            if obj.get("pricing") is not None
            else None
        })
        return _obj


