# coding: utf-8

"""
    WHMCS API

    Python client for the WHMCS API.  WHMCS (Web Host Manager Complete Solution) provides a single API endpoint that handles multiple operations through different 'action' parameters. This specification presents each action as an independent path while routing all requests to the /api.php endpoint. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class InvoiceInfo(BaseModel):
    """
    InvoiceInfo
    """ # noqa: E501
    id: Optional[StrictInt] = Field(default=None, description="The invoice ID")
    userid: Optional[StrictInt] = Field(default=None, description="The client ID linked to the invoice")
    firstname: Optional[StrictStr] = None
    lastname: Optional[StrictStr] = None
    companyname: Optional[StrictStr] = None
    invoicenum: Optional[StrictStr] = None
    var_date: Optional[StrictStr] = Field(default=None, description="The invoice date (YYYY-MM-DD, may be 0000-00-00)", alias="date")
    duedate: Optional[StrictStr] = Field(default=None, description="The invoice due date (YYYY-MM-DD, may be 0000-00-00)")
    datepaid: Optional[StrictStr] = None
    last_capture_attempt: Optional[StrictStr] = None
    date_refunded: Optional[StrictStr] = None
    date_cancelled: Optional[StrictStr] = None
    subtotal: Optional[StrictStr] = None
    credit: Optional[StrictStr] = None
    tax: Optional[StrictStr] = None
    tax2: Optional[StrictStr] = None
    total: Optional[StrictStr] = None
    taxrate: Optional[StrictStr] = None
    taxrate2: Optional[StrictStr] = None
    status: Optional[StrictStr] = None
    paymentmethod: Optional[StrictStr] = None
    notes: Optional[StrictStr] = None
    created_at: Optional[StrictStr] = None
    updated_at: Optional[StrictStr] = None
    currencycode: Optional[StrictStr] = None
    currencyprefix: Optional[StrictStr] = None
    currencysuffix: Optional[StrictStr] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["id", "userid", "firstname", "lastname", "companyname", "invoicenum", "date", "duedate", "datepaid", "last_capture_attempt", "date_refunded", "date_cancelled", "subtotal", "credit", "tax", "tax2", "total", "taxrate", "taxrate2", "status", "paymentmethod", "notes", "created_at", "updated_at", "currencycode", "currencyprefix", "currencysuffix"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InvoiceInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InvoiceInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "userid": obj.get("userid"),
            "firstname": obj.get("firstname"),
            "lastname": obj.get("lastname"),
            "companyname": obj.get("companyname"),
            "invoicenum": obj.get("invoicenum"),
            "date": obj.get("date"),
            "duedate": obj.get("duedate"),
            "datepaid": obj.get("datepaid"),
            "last_capture_attempt": obj.get("last_capture_attempt"),
            "date_refunded": obj.get("date_refunded"),
            "date_cancelled": obj.get("date_cancelled"),
            "subtotal": obj.get("subtotal"),
            "credit": obj.get("credit"),
            "tax": obj.get("tax"),
            "tax2": obj.get("tax2"),
            "total": obj.get("total"),
            "taxrate": obj.get("taxrate"),
            "taxrate2": obj.get("taxrate2"),
            "status": obj.get("status"),
            "paymentmethod": obj.get("paymentmethod"),
            "notes": obj.get("notes"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "currencycode": obj.get("currencycode"),
            "currencyprefix": obj.get("currencyprefix"),
            "currencysuffix": obj.get("currencysuffix")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


