# coding: utf-8

"""
    WHMCS API

    Python client for the WHMCS API.  WHMCS (Web Host Manager Complete Solution) provides a single API endpoint that handles multiple operations through different 'action' parameters. This specification presents each action as an independent path while routing all requests to the /api.php endpoint. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from whmcs_client.models.tld_pricing_info_addons import TldPricingInfoAddons
from typing import Optional, Set
from typing_extensions import Self

class TldPricingInfo(BaseModel):
    """
    TldPricingInfo
    """ # noqa: E501
    tld: Optional[StrictStr] = Field(default=None, description="The TLD")
    categories: Optional[List[StrictStr]] = Field(default=None, description="The TLD categories")
    addons: Optional[TldPricingInfoAddons] = None
    group: Optional[StrictStr] = Field(default=None, description="The TLD group")
    register: Optional[Dict[str, StrictStr]] = Field(default=None, description="Registration pricing keyed by term")
    transfer: Optional[Dict[str, StrictStr]] = Field(default=None, description="Transfer pricing keyed by term")
    renew: Optional[Dict[str, StrictStr]] = Field(default=None, description="Renewal pricing keyed by term")
    grace_period: Optional[StrictStr] = Field(default=None, description="The grace period, when configured")
    redemption_period: Optional[StrictStr] = Field(default=None, description="The redemption period, when configured")
    __properties: ClassVar[List[str]] = ["tld", "categories", "addons", "group", "register", "transfer", "renew", "grace_period", "redemption_period"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TldPricingInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of addons
        if self.addons:
            _dict['addons'] = self.addons.to_dict()
        # set to None if grace_period (nullable) is None
        # and model_fields_set contains the field
        if self.grace_period is None and "grace_period" in self.model_fields_set:
            _dict['grace_period'] = None

        # set to None if redemption_period (nullable) is None
        # and model_fields_set contains the field
        if self.redemption_period is None and "redemption_period" in self.model_fields_set:
            _dict['redemption_period'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TldPricingInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "tld": obj.get("tld"),
            "categories": obj.get("categories"),
            "addons": TldPricingInfoAddons.from_dict(obj["addons"]) if obj.get("addons") is not None else None,
            "group": obj.get("group"),
            "register": obj.get("register"),
            "transfer": obj.get("transfer"),
            "renew": obj.get("renew"),
            "grace_period": obj.get("grace_period"),
            "redemption_period": obj.get("redemption_period")
        })
        return _obj


