# coding: utf-8

"""
    WHMCS API

    Python client for the WHMCS API.  WHMCS (Web Host Manager Complete Solution) provides a single API endpoint that handles multiple operations through different 'action' parameters. This specification presents each action as an independent path while routing all requests to the /api.php endpoint. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class TransactionInfo(BaseModel):
    """
    TransactionInfo
    """ # noqa: E501
    id: Optional[StrictInt] = Field(default=None, description="The transaction ID")
    userid: Optional[StrictInt] = Field(default=None, description="The client ID")
    currency: Optional[StrictInt] = Field(default=None, description="The currency ID")
    gateway: Optional[StrictStr] = Field(default=None, description="The payment gateway")
    var_date: Optional[StrictStr] = Field(default=None, description="The transaction date and time", alias="date")
    description: Optional[StrictStr] = Field(default=None, description="The transaction description")
    amountin: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The amount in")
    fees: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The transaction fees")
    amountout: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The amount out")
    rate: Optional[StrictStr] = Field(default=None, description="The exchange rate")
    transid: Optional[StrictStr] = Field(default=None, description="The transaction identifier")
    invoiceid: Optional[StrictInt] = Field(default=None, description="The invoice ID")
    refundid: Optional[StrictInt] = Field(default=None, description="The refund ID")
    __properties: ClassVar[List[str]] = ["id", "userid", "currency", "gateway", "date", "description", "amountin", "fees", "amountout", "rate", "transid", "invoiceid", "refundid"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TransactionInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TransactionInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "userid": obj.get("userid"),
            "currency": obj.get("currency"),
            "gateway": obj.get("gateway"),
            "date": obj.get("date"),
            "description": obj.get("description"),
            "amountin": obj.get("amountin"),
            "fees": obj.get("fees"),
            "amountout": obj.get("amountout"),
            "rate": obj.get("rate"),
            "transid": obj.get("transid"),
            "invoiceid": obj.get("invoiceid"),
            "refundid": obj.get("refundid")
        })
        return _obj


