# coding: utf-8

"""
    WHMCS API

    Python client for the WHMCS API.  WHMCS (Web Host Manager Complete Solution) provides a single API endpoint that handles multiple operations through different 'action' parameters. This client supports various WHMCS operations for managing clients, orders, and other resources.  Authentication is handled through username/password or API credentials. All requests are sent as form-encoded data to the /api.php endpoint. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class UpdateClientRequest(BaseModel):
    """
    UpdateClientRequest
    """ # noqa: E501
    username: StrictStr = Field(description="Admin username/API identifier")
    password: StrictStr = Field(description="Admin password/API secret")
    accesskey: Optional[StrictStr] = Field(default=None, description="Optional API access key")
    responsetype: Optional[StrictStr] = Field(default='json', description="Response format")
    action: StrictStr = Field(description="Must be 'UpdateClient'")
    clientid: Optional[StrictInt] = Field(default=None, description="The ID of the client to update")
    clientemail: Optional[StrictStr] = Field(default=None, description="The email address of the client to update")
    firstname: Optional[StrictStr] = Field(default=None, description="First name of the client")
    lastname: Optional[StrictStr] = Field(default=None, description="Last name of the client")
    companyname: Optional[StrictStr] = Field(default=None, description="Company name")
    email: Optional[StrictStr] = Field(default=None, description="Email address of the client")
    address1: Optional[StrictStr] = Field(default=None, description="Address line 1")
    address2: Optional[StrictStr] = Field(default=None, description="Address line 2")
    city: Optional[StrictStr] = Field(default=None, description="City")
    state: Optional[StrictStr] = Field(default=None, description="State")
    postcode: Optional[StrictStr] = Field(default=None, description="Postal code")
    country: Optional[StrictStr] = Field(default=None, description="2 character ISO country code")
    phonenumber: Optional[StrictStr] = Field(default=None, description="Phone number")
    tax_id: Optional[StrictStr] = Field(default=None, description="Client's tax ID")
    currency: Optional[StrictInt] = Field(default=None, description="Currency ID")
    groupid: Optional[StrictInt] = Field(default=None, description="Client group ID")
    customfields: Optional[StrictStr] = Field(default=None, description="Base64 encoded serialized array of custom field values")
    language: Optional[StrictStr] = Field(default=None, description="Default language setting")
    clientip: Optional[StrictStr] = Field(default=None, description="IP address of the user")
    notes: Optional[StrictStr] = Field(default=None, description="Admin only notes")
    status: Optional[StrictStr] = Field(default=None, description="The status (e.g., Active)")
    paymentmethod: Optional[StrictStr] = Field(default=None, description="The default payment method")
    email_preferences_general: Optional[StrictBool] = Field(default=None, description="Receive general emails")
    email_preferences_product: Optional[StrictBool] = Field(default=None, description="Receive product emails")
    email_preferences_domain: Optional[StrictBool] = Field(default=None, description="Receive domain emails")
    email_preferences_invoice: Optional[StrictBool] = Field(default=None, description="Receive invoice emails")
    email_preferences_support: Optional[StrictBool] = Field(default=None, description="Receive support emails")
    email_preferences_affiliate: Optional[StrictBool] = Field(default=None, description="Receive affiliate emails")
    marketingoptin: Optional[StrictBool] = Field(default=None, description="Opt-in to marketing emails")
    clearcreditcard: Optional[StrictBool] = Field(default=None, description="Clear stored credit card details")
    skipvalidation: Optional[StrictBool] = Field(default=None, description="Ignore required field validation")
    latefeeoveride: Optional[StrictBool] = Field(default=None, description="Override Late Fees setting")
    overideduenotices: Optional[StrictBool] = Field(default=None, description="Override Overdue Notices setting")
    taxexempt: Optional[StrictBool] = Field(default=None, description="Exempt from tax collections")
    separateinvoices: Optional[StrictBool] = Field(default=None, description="Group items into one invoice")
    disableautocc: Optional[StrictBool] = Field(default=None, description="Enable/disable automatic credit card processing")
    overrideautoclose: Optional[StrictBool] = Field(default=None, description="Enable/disable automatic account closure")
    __properties: ClassVar[List[str]] = ["username", "password", "accesskey", "responsetype", "action", "clientid", "clientemail", "firstname", "lastname", "companyname", "email", "address1", "address2", "city", "state", "postcode", "country", "phonenumber", "tax_id", "currency", "groupid", "customfields", "language", "clientip", "notes", "status", "paymentmethod", "email_preferences_general", "email_preferences_product", "email_preferences_domain", "email_preferences_invoice", "email_preferences_support", "email_preferences_affiliate", "marketingoptin", "clearcreditcard", "skipvalidation", "latefeeoveride", "overideduenotices", "taxexempt", "separateinvoices", "disableautocc", "overrideautoclose"]

    @field_validator('responsetype')
    def responsetype_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['json', 'xml']):
            raise ValueError("must be one of enum values ('json', 'xml')")
        return value

    @field_validator('action')
    def action_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['UpdateClient']):
            raise ValueError("must be one of enum values ('UpdateClient')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdateClientRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdateClientRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "username": obj.get("username"),
            "password": obj.get("password"),
            "accesskey": obj.get("accesskey"),
            "responsetype": obj.get("responsetype") if obj.get("responsetype") is not None else 'json',
            "action": obj.get("action"),
            "clientid": obj.get("clientid"),
            "clientemail": obj.get("clientemail"),
            "firstname": obj.get("firstname"),
            "lastname": obj.get("lastname"),
            "companyname": obj.get("companyname"),
            "email": obj.get("email"),
            "address1": obj.get("address1"),
            "address2": obj.get("address2"),
            "city": obj.get("city"),
            "state": obj.get("state"),
            "postcode": obj.get("postcode"),
            "country": obj.get("country"),
            "phonenumber": obj.get("phonenumber"),
            "tax_id": obj.get("tax_id"),
            "currency": obj.get("currency"),
            "groupid": obj.get("groupid"),
            "customfields": obj.get("customfields"),
            "language": obj.get("language"),
            "clientip": obj.get("clientip"),
            "notes": obj.get("notes"),
            "status": obj.get("status"),
            "paymentmethod": obj.get("paymentmethod"),
            "email_preferences_general": obj.get("email_preferences_general"),
            "email_preferences_product": obj.get("email_preferences_product"),
            "email_preferences_domain": obj.get("email_preferences_domain"),
            "email_preferences_invoice": obj.get("email_preferences_invoice"),
            "email_preferences_support": obj.get("email_preferences_support"),
            "email_preferences_affiliate": obj.get("email_preferences_affiliate"),
            "marketingoptin": obj.get("marketingoptin"),
            "clearcreditcard": obj.get("clearcreditcard"),
            "skipvalidation": obj.get("skipvalidation"),
            "latefeeoveride": obj.get("latefeeoveride"),
            "overideduenotices": obj.get("overideduenotices"),
            "taxexempt": obj.get("taxexempt"),
            "separateinvoices": obj.get("separateinvoices"),
            "disableautocc": obj.get("disableautocc"),
            "overrideautoclose": obj.get("overrideautoclose")
        })
        return _obj


